select
    TIME,
    TEMPERATURE_2M_C,
    WIND_SPEED_10M_M_S,
    WIND_SPEED_80M_M_S,
    SHORTWAVE_RADIATION_W_M2,
    DIRECT_RADIATION_W_M2,
    DIFFUSE_RADIATION_W_M2,
    PRECIPITATION_MM,
    CLOUDCOVER as CLOUD_COVER,
    PRESSURE_MSL_HPA,
    RAIN_MM,
    SNOWFALL_CM,
    POSTAL_CODE,
    COUNTRY_ENGLISH,
    LATITUDE,
    LONGITUDE
from {{ source('raw_power_generation', 'dim_weather') }}
